language: php

php:
  - 5.6

matrix:
  include:
    - php: 5.6
      env: SYMFONY_VERSION=^2.8
    - php: 5.6
      env: SYMFONY_VERSION=^3.0
    - php: 7.1
      env: SYMFONY_VERSION=^4.0

before_install:
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/framework-bundle:${SYMFONY_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev "symfony/console:${SYMFONY_VERSION}" --no-update; fi;

before_script:
  - COMPOSER_MEMORY_LIMIT=-1 composer update